# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:/usr/local/opt/python/libexec/bin:$PATH

# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME=robbyrussell

plugins=(git git-flow github osx tmux tmuxinator)

export LC_ALL="en_US.UTF-8"
export LANG=en_US.UTF-8
export EDITOR=vim

source $ZSH/oh-my-zsh.sh

unsetopt correct_all

# User configuration

alias git=hub
alias commit="git commit -S -m"
